%====================== format/*              ===============================
Goal: format(X,"this % the %'st % test",is,1,"small")
X=this is the 1'st small test
1 Solution

Goal: format(X,"REALS: Default=%, Exp=%e, Shortest=%g",99E9,99E9,99E9)
X=REALS: Default=98999999999.99999989, Exp=9.9E+10, Shortest=9.9E+10
1 Solution

Goal: format(X,"char=%c, int=%, unsigned=%u, hex=%x",97,-1,-1,-1)
X=char=a, int=-1, unsigned=65535, hex=FFFF
1 Solution
