%====================== frontstr/4            ===============================
Goal: frontstr(3,"All boys do fine",STR1,STR2)
STR1=All, STR2= boys do fine
1 Solution
Goal: frontstr(9,"All boys do fine",STR1,STR2)
STR1=All boys , STR2=do fine
1 Solution
Goal: frontstr(0,"All boys do fine",STR1,STR2)
STR1=, STR2=All boys do fine
1 Solution
Goal: frontstr(-1,"All boys do fine",STR1,STR2)
No Solution
Goal: frontstr(20,"All boys do fine",STR1,STR2)
No Solution
