%====================== envsymbol/2           ===============================
C:\PROLOG >set bgi_path=c:\prolog\bgi

C:\PROLOG >set
COMSPEC=C:\COMMAND.COM
PROSYS=C:\PROLOG\OLD.SYS
PATH=C:\DOS;C:\PROLOG
PROMPT=$p $g
BGI_PATH=c:\prolog\bgi

C:\PROLOG >prolog

+++++++ Press Run +++++++++

Goal: envsymbol(path,PATH)
PATH=C:\DOS;C:\PSYS
1 Solution
Goal: envsymbol(bgi_path,PATH)
PATH=C:\PROLOG\BGI
1 Solution
