%====================== errormsg/4            ===============================
Goal: errormsg("prolog.err",1000,HELP,EHELP)
HELP=1000  The arguments in 'makewindow' are illegal.,
EHELP=Check that
      - the window number is in the range 1 .. 127
      - StartRow+NoOfRows <= no. of rows on screen (usually 25 or 43)
      - StartCol+NoOfCols <= no. of cols on screen (usually 80 or 120)
1 Solution
Goal:
