-- MySQL Script generated by MySQL Workbench
-- 12/02/14 22:49:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema graveyards_management_app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `graveyards_management_app` ;

-- -----------------------------------------------------
-- Schema graveyards_management_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `graveyards_management_app` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `graveyards_management_app` ;

-- -----------------------------------------------------
-- Table `graveyards_management_app`.`graveyards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`graveyards` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`graveyards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `graveyards_management_app`.`graveyards` (`name` ASC);

CREATE INDEX `deleted_index` ON `graveyards_management_app`.`graveyards` (`deleted` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`parcels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`parcels` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`parcels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `graveyard_id` INT NULL,
  `number` INT UNSIGNED NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_parcel_graveyard`
    FOREIGN KEY (`graveyard_id`)
    REFERENCES `graveyards_management_app`.`graveyards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `graveyard_index` ON `graveyards_management_app`.`parcels` (`graveyard_id` ASC);

CREATE INDEX `deleted_index` ON `graveyards_management_app`.`parcels` (`deleted` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`owners` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`owners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(50) NULL,
  `address` VARCHAR(200) NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `deleted_index` ON `graveyards_management_app`.`owners` (`deleted` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`graves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`graves` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`graves` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parcel_id` INT NULL,
  `number` BIGINT UNSIGNED NOT NULL,
  `surface` FLOAT NULL,
  `remarks` VARCHAR(500) NULL,
  `image_uri` VARCHAR(100) NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_graves_parcels`
    FOREIGN KEY (`parcel_id`)
    REFERENCES `graveyards_management_app`.`parcels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `parcel_index` ON `graveyards_management_app`.`graves` (`parcel_id` ASC);

CREATE INDEX `deleted_index` ON `graveyards_management_app`.`graves` (`deleted` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`concessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`concessions` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`concessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `grave_id` INT NOT NULL,
  `number` BIGINT NOT NULL,
  `date` DATE NULL,
  `period` INT UNSIGNED NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_owners_concessions`
    FOREIGN KEY (`owner_id`)
    REFERENCES `graveyards_management_app`.`owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_graves_concessions`
    FOREIGN KEY (`grave_id`)
    REFERENCES `graveyards_management_app`.`graves` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `owner_index` ON `graveyards_management_app`.`concessions` (`owner_id` ASC);

CREATE INDEX `id_idx` ON `graveyards_management_app`.`concessions` (`grave_id` ASC);

CREATE INDEX `grave_index` ON `graveyards_management_app`.`concessions` (`grave_id` ASC);

CREATE INDEX `deleted_index` ON `graveyards_management_app`.`concessions` (`deleted` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`receipts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`receipts` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`receipts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `concession_id` INT NOT NULL,
  `recepit_number` BIGINT NOT NULL,
  `starting_date` DATE NULL,
  `ending_date` DATE NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_concessions_receipts`
    FOREIGN KEY (`concession_id`)
    REFERENCES `graveyards_management_app`.`concessions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_idx` ON `graveyards_management_app`.`receipts` (`concession_id` ASC);

CREATE INDEX `deleted_index` ON `graveyards_management_app`.`receipts` (`deleted` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`deads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`deads` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`deads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grave_id` INT NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(50) NULL,
  `religion` VARCHAR(50) NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_dead_graves`
    FOREIGN KEY (`grave_id`)
    REFERENCES `graveyards_management_app`.`graves` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `grave_index` ON `graveyards_management_app`.`deads` (`grave_id` ASC);

CREATE INDEX `deleted_index` ON `graveyards_management_app`.`deads` (`deleted` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`funerals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`funerals` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`funerals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dead_id` INT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_deads_funerals`
    FOREIGN KEY (`dead_id`)
    REFERENCES `graveyards_management_app`.`deads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_idx` ON `graveyards_management_app`.`funerals` (`dead_id` ASC);

CREATE INDEX `deleted_index` ON `graveyards_management_app`.`funerals` (`deleted` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`monuments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`monuments` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`monuments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grave_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_monuments_graves`
    FOREIGN KEY (`grave_id`)
    REFERENCES `graveyards_management_app`.`graves` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `grave_id_UNIQUE` ON `graveyards_management_app`.`monuments` (`grave_id` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`complaints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`complaints` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`complaints` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` BIGINT NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `number_index` ON `graveyards_management_app`.`complaints` (`number` ASC);

CREATE INDEX `deleted_index` ON `graveyards_management_app`.`complaints` (`deleted` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`states` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`requests` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `state_id` INT NULL,
  `current_number` BIGINT NULL,
  `registration_date` DATE NULL,
  `infocet_number` BIGINT NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_requests_states`
    FOREIGN KEY (`state_id`)
    REFERENCES `graveyards_management_app`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `state_index` ON `graveyards_management_app`.`requests` (`state_id` ASC);

CREATE INDEX `deleted_index` ON `graveyards_management_app`.`requests` (`deleted` ASC);


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`users` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graveyards_management_app`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graveyards_management_app`.`transactions` ;

CREATE TABLE IF NOT EXISTS `graveyards_management_app`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `document_number` BIGINT NULL,
  `modification_details` VARCHAR(500) NULL,
  `before` VARCHAR(500) NULL,
  `after` VARCHAR(500) NULL,
  `table` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_transactions`
    FOREIGN KEY (`user_id`)
    REFERENCES `graveyards_management_app`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_transactions_idx` ON `graveyards_management_app`.`transactions` (`user_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
